### ISSUE TITLE
Error installing  pod

### ISSUE THREAD

**Issue by Akateason** [jdmunro/react-native-spotlight-search#19]
[!] Error installing react-native-spotlight-search
[!] /usr/bin/git clone https://github.com/jdmunro/react-native-spotlight-search.git /var/folders/cf/55wtc_bj5wq7w4k9t5wz5s180000gn/T/d20200428-74531-8mtg0e --template= --single-branch --depth 1 --branch v1.3.0

**Comment by Akateason** [comment]
project don't have tag 1.3.0

**Comment by jdmunro** [comment]
I'm unable to reproduce this issue - feel free to re-open if you still have problems!
