### ISSUE TITLE
thumbnailData base64 string not working

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [jdmunro/react-native-spotlight-search#47]
When I provide a base64 string to the thumbnailData property it is not taken into account.
What I see is the app icon not the icon I provide.

```
const item = {
  {
    uniqueIdentifier: '1',
    title: 'title',
    contentDescription: 'desc',
    domain: item.domain,
    keywords: [
      'test', 'key'
    ],
    thumbnailData: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAApgAAAKYB3X3/OAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAANCSURBVEiJtZZPbBtFFMZ/M7ubXdtdb1xSFyeilBapySVU8h8OoFaooFSqiihIVIpQBKci6KEg9Q6H9kovIHoCIVQJJCKE1ENFjnAgcaSGC6rEnxBwA04Tx43t2FnvDAfjkNibxgHxnWb2e/u992bee7tCa00YFsffekFY+nUzFtjW0LrvjRXrCDIAaPLlW0nHL0SsZtVoaF98mLrx3pdhOqLtYPHChahZcYYO7KvPFxvRl5XPp1sN3adWiD1ZAqD6XYK1b/dvE5IWryTt2udLFedwc1+9kLp+vbbpoDh+6TklxBeAi9TL0taeWpdmZzQDry0AcO+jQ12RyohqqoYoo8RDwJrU+qXkjWtfi8Xxt58BdQuwQs9qC/afLwCw8tnQbqYAPsgxE1S6F3EAIXux2oQFKm0ihMsOF71dHYx+f3NND68ghCu1YIoePPQN1pGRABkJ6Bus96CutRZMydTl+TvuiRW1m3n0eDl0vRPcEysqdXn+jsQPsrHMquGeXEaY4Yk4wxWcY5V/9scqOMOVUFthatyTy8QyqwZ+kDURKoMWxNKr2EeqVKcTNOajqKoBgOE28U4tdQl5p5bwCw7BWquaZSzAPlwjlithJtp3pTImSqQRrb2Z8PHGigD4RZuNX6JYj6wj7O4TFLbCO/Mn/m8R+h6rYSUb3ekokRY6f/YukArN979jcW+V/S8g0eT/N3VN3kTqWbQ428m9/8k0P/1aIhF36PccEl6EhOcAUCrXKZXXWS3XKd2vc/TRBG9O5ELC17MmWubD2nKhUKZa26Ba2+D3P+4/MNCFwg59oWVeYhkzgN/JDR8deKBoD7Y+ljEjGZ0sosXVTvbc6RHirr2reNy1OXd6pJsQ+gqjk8VWFYmHrwBzW/n+uMPFiRwHB2I7ih8ciHFxIkd/3Omk5tCDV1t+2nNu5sxxpDFNx+huNhVT3/zMDz8usXC3ddaHBj1GHj/As08fwTS7Kt1HBTmyN29vdwAw+/wbwLVOJ3uAD1wi/dUH7Qei66PfyuRj4Ik9is+hglfbkbfR3cnZm7chlUWLdwmprtCohX4HUtlOcQjLYCu+fzGJH2QRKvP3UNz8bWk1qMxjGTOMThZ3kvgLI5AzFfo379UAAAAASUVORK5CYII='
  }
```

This should be correct, right? Or did I make a mistake?

**Comment by mariomurrent-softwaresolutions** [comment]
@jdmunro any ideas why this is not working?

**Comment by jdmunro** [comment]
@mariomurrent-softwaresolutions Are you sure that's a valid image? If I put it [here (web)](https://jsfiddle.net/9tpnrgqb/1/) it doesn't render. This format looks a bit strange to me: `W / n + uMPFiRwHB2I7ih8ciHFxIkd / 3 Omk5tCDV1t + 2 nNu5sxxpDFNx + huNhVT3 / zMDz8us`

**Comment by mariomurrent-softwaresolutions** [comment]
Hi, just remove the white spaces, GitHub formats the string in a strange way 😞

**Comment by mariomurrent-softwaresolutions** [comment]
@jdmunro Have you every tried it yourself on a real iOS Device?

**Comment by mariomurrent-softwaresolutions** [comment]
@jdmunro any updates on this one?

**Comment by jedashford** [comment]
Something is wrong with your base64 encoded data. Maybe strip off the `data:image/png;base64,`

Here is one of our base64 encoded images which works just great:
`/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAcHBwcHBwgJCQgLDAsMCxAPDg4PEBkSExITEhklFxsXFxsXJSEoIR4hKCE7LykpLztFOjc6RVNKSlNpY2mJibgBBwcHBwcHCAkJCAsMCwwLEA8ODg8QGRITEhMSGSUXGxcXGxclISghHiEoITsvKSkvO0U6NzpFU0pKU2ljaYmJuP/AABEIAGQAZAMBIgACEQEDEQH/xAB+AAABBQEBAQAAAAAAAAAAAAAFAAMEBgcCAQgQAAIBAwQBAwIDCAIDAAAAAAECAwAEEQUSITFBEyJRBmEjcZEUFTJCQ1KBsTOSYqHxAQEBAQEBAAAAAAAAAAAAAAABAgADBBEBAQACAwEBAQAAAAAAAAAAAQACERIxQSEDUf/aAAwDAQACEQMRAD8AOQ/UGpogAueAABwKeTWdRZ+bl6rcILHGKM2ohiRw4BY8A/FGiPtouhauJoCtwuSvO+in780gf1R/0NZ/ayG3R8N7TEx/z1QOSVx5NRw+tfL4WsnXNG8yj/oaizfUukJhIjukbhRtxWUTXXoxM7E8Cqkl1eTO1wH7yACM0IEm1tD1O5ttSvGIvFZycbQjEKB+QNN26Pp4d/XZJONi7CVdT55rLiZo5w7s+N3LKfcKvq69FN6NpdymXYBsuPJBHmnlqOFOeZWJdlBLZzxjBNDNSMD/AMJBwo5C4qftVv4TxQm8UDOK6UagDmP3FuSOqYt1tAwM4B+xHFSXhPNQpIj8mhgJ+WSyLnai48eylUP0m8E0qnZVxrnGRGc71Jz4NSCzSZOaZKK/T7v8YpyRzHnC+K6eQfG7F00aspJ5FMCbfUORnOM9V0hGKlrT0o2s3AS0K4yznFQEKwx28LDBKDJHgmiF4hlt3AA6zUWea3jWJnkADICM1w/Tsu35HcJvZY42KFvdUSzuUjmIkL4AJG3sfcV47xSTSEEGoyxyNeRCLGQP9+K05WogyQwQM5zviV1bGAynzQ2Zvdn5pl7qYJHBIxIjRUXPhR4phmGRzXbG873NSFVzQ+Tk81OumG8jrqhzMOazBeBD4WlTZYA90qiqurtHb7/Ub3g421zb3EN3MsLMIwemPPNeawDeypPAMllAkUeHFBYbZzLGSylQcsAeaozUniDWS5j0+NFE9z6bAdKu8t9x1St/3GysWa6wo7yndVy/I9THkKKgLNLGxQMQJF5FQq+1dVq1bVdOsmhSPTo39SBHJZ2zz+WKoyXKNNICoEqg+nzxtPjmuNQaQzBs/wAgH6UMlaGfAcEN0CO6hNV4t7cyqsuf6nWBV7sfpW7S2t78IJiyZ/DbcYy3hh81notlhcBcs2OSasOnapd6dIPTlILEFhng/nSeasne45LHtJDA5plyFxuHVXV9R0P6i9FJ2mhu9gQS8FTjrcKB6xoN5pkSSuUeKQ4SRGyCa6GYurk4oVbkcSElqZWFJnCZA+9NSggVHiuWhLtjPFVRPvakOQBkUqZjv5WBJi80qfkX0+LeyDFP2aPAXdyoNZBq0dtb3l4sJBX1GII+Aeq0n6gvRp8RIbBeIov2+TWK3dwxkOT+RrzY3pymLt/UuvzUA/pUd/8AkQj5xXAkL30mfGKkyxYZPzqvY8ol1B6yMAMuOVqqs26QfC91cwT66Y+Cf0oVe29t+0y7IhydzUrBCjMJB+GhX5Ytkf6p2zQu5OcheTXM+FIVR18VPgjMcSp5bk1jqzToTlsg9VqtrOmofTF1ZTcywQiVPJ9vuz+hrKshQAP8Cr19PagouYEYdoYnz5H/AMOKl8k9qJcITIVFS7LRUdllvjJHCegmN7fcZ8VMnsiuqSxtnbG7BseQpqfK5c81eWVOOG/sQt30C2iWNNIikA/mlYs5pUGGKVTXab9Yt6tranO2TDZFY/cLIrE7l5P9taj9bOwu41A7iBFZ1eoIIgf5mOM1A6sm2rU94kUyuGAbAV1PYx0aPm4jl6YdGgDaeGJJwxPNeLZunQI+4p5Ys8MogbkCUc4wlC3vIy8hb+7FSEsgvvJYmodwShIw/H/jSItuCExE6yT5JHHNFl9zvjwuKBeorSId/XeRipTXpiiZlUHzVUsbRs5l8DIFWTSPZLFiQgPtAO3PuHI/91R3nb9jgjDYZjz/ALNHdNlKIVkB+xzxUslaL9Ctw84BAnVD+gxQsyZbaal3Ny0sMIbtVoFcTMi7geQcioV3WGiMBMilXMEgkhjbOMqDSp3Frev2A1CyMm38SAE9dgdisk1BUMWXAO7+HnrHdbXd30dvHMzuBtIr53+pr6GbU7j0eIgfao6oxjL5Pi1Hqop6Iz3XSwx+swGcLXFpcb4oy7dcKfmnRIoMjfcU8SOTNsdwb2qQDiq9dqFbbl1PfBqXNePKpigBZmbsU0bf1YEleQ79uaNfysy+fYLIrFSN5wfnFNGMugQsdtTGgJXI77pl7eTcoUE5qxQpeK0qwjCOyk54GM848VabEOuVwMr2KF2enrbxmSTmUggL8D7ijkACfjAjhevk1lbaN/J65kIwPtQW7bfE4+BT096jSBW4NN3SZgbb21Qd1eRW19ttEOeEFKuYY/TiRPgYpUamsX1hdTb42DYPCkjyKzmK3jubhjJk5kIpUqvHq5PcaCI1uV2gBMqoHGBQHU3aFnVDgHv70qVPjJ3TFjWKHCjH4Y585amnYrE/2WlSrRQhMxbZgAYFH9GtYrvUbKCTOySaNGx8E4pUqGSm3sKRLBIud0gJNQp2KxLjjIpUq0ncAumO9T9qJaYqvbxgj5NKlTL5F9xBIpUqVbRF/9k=`

**Comment by mariomurrent-softwaresolutions** [comment]
Hello, alright, I will try this out and let you know

**Comment by mariomurrent-softwaresolutions** [comment]
Tried it, but still not working. I'm only seeing the default app image

**Comment by mariomurrent-softwaresolutions** [comment]
Seems to be magically fixed
