### ISSUE TITLE
Does not work anymore with react-native 0.68.1

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [jdmunro/react-native-spotlight-search#49]
I upgraded to react-native 0.68.1 but the search item tapped listener ist not triggered anymore.

Any idea why?

**Comment by jedashford** [comment]
Works for us in "react-native": "0.68.5"

**Comment by mariomurrent-softwaresolutions** [comment]
Okay, I upgraded to RN 0.70 - lets see if it works

**Comment by mariomurrent-softwaresolutions** [comment]
Does not work after the upgrade

**Comment by mariomurrent-softwaresolutions** [comment]
Seems to be magically solved
