### ISSUE TITLE
Callback on Release called just once

### ISSUE THREAD

**Issue by zcei** [jdmunro/react-native-spotlight-search#5]
Hej there,

with your module it has been a pleasure to implement spotlight search :)

When I built it the first time in Release mode I faced a surprise, though:
Compared to Development mode, where it responds to multiple interactions, in Release it only reacts to *the first* user interaction.

I solved it by recursively listening for user taps, but I wonder whether that is a bug in your module, or a constraint by Apple.

While looking at your code I found something with an activity queue, so I assume your intention was to support multiple interactions. But here my Objective C skills end.

(`react-native@0.33.1`, `react-native-spotlight-search@0.2.0`)

**Comment by jdmunro** [comment]
Thanks for reporting the issue!

Does this problem happen even in the example project I provided? I will try and take a look at this sometime this week 👍

**Comment by jdmunro** [comment]
Okay, I've worked out what the issue is. The problem is caused by the way we're trying to use the callback more than once from inside the native code.

Spotted this in the [React Native docs](https://facebook.github.io/react-native/docs/native-modules-ios.html#callbacks):

> A native module is supposed to invoke its callback only once.

The solution is to use the [event dispatcher](https://facebook.github.io/react-native/docs/native-modules-ios.html#sending-events-to-javascript) instead.

I think we can fix this without needing to change the public API.

**Comment by jdmunro** [comment]
I've published version 0.2.1 which I believe fixes the problem you are experiencing. When you get a few minutes, would you mind checking and let me know if the problem has been resolved?

**Comment by zcei** [comment]
Oh well, I was just trying to get everything set up to surprise you with a PR, but somehow I wasn't able to get the example running `RCTBridge.h`

Going to try out your fix now 👍

**Comment by jdmunro** [comment]
It's possible you may run into errors as I noticed you are using a more
modern version of React Native than the example project uses.

If that's the case we can also fix that.

**Comment by zcei** [comment]
As the project I'm working on builds totally fine you don't have to look into the example right now. 

And there the fix works like a charm 👌 
That said, may I offer you some stickers for your very prompt response? 🎁

**Comment by jdmunro** [comment]
Happy to help. Also happy to accept stickers ⭐️

If your project ends up on the App Store and you're happy for it to be included, I can add it to a showcase in this repo.
